### ISSUE TITLE
Error when creating tables in MySQL 5.7.26

### ISSUE THREAD

**Issue by johndkn** [EFTEC/StateMachineOne#3]
Hello,

We have the following PHP error with "$smachine->createDbTable(true);"

> Fatal error: Uncaught Exception: Exception rawCREATE TABLE `chopsuey_jobs` (`idjob` INT NOT NULL AUTO_INCREMENT,`idactive` int,`idstate` int,`dateinit` timestamp,`datelastchange` timestamp,`dateexpired` timestamp,`dateend` timestamp,`text_job` MEDIUMTEXT,`customerpresent` int,`addressnotfound` int,`signeddeliver` int,`abort` int,`instock` int,`picked` int, PRIMARY KEY(`idjob`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8. in /var/www/dev/vendor/eftec/pdoone/lib/PdoOne.php:565

When we try the create request in mysql (v5.7.26), we have this error : 

> Invalid default value for 'datelastchange'

I believe all "timestamp" columns need to have a default value in this request

**Comment by jorgecc** [comment]
Done in #2.3 too.  I added a default value for timestamp.
