### ISSUE TITLE
WebUI on HTTPS websites

### ISSUE THREAD

**Issue by johndkn** [EFTEC/StateMachineOne#4]
Hello,

On HTTPS websites, browser refuses to load "http://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" (line 1332 of file vendor/eftec/statemachineone/lib/StateMachineOne.php)

The quick fix is to replace in the link "http" with "https"

<img width="1309" alt="Capture d’écran 2019-12-26 à 17 15 09" src="https://user-images.githubusercontent.com/20562331/71490819-54be6c00-2803-11ea-952c-5fa44ba08c5c.png">

**Comment by jorgecc** [comment]
Done in 2.3
