### ISSUE TITLE
Error when Setting Field Value

### ISSUE THREAD

**Issue by johndkn** [EFTEC/StateMachineOne#5]
When I click on "Set Field Value" in the UI (ChopSuey example), I get the following error :

> Warning: array_values() expects parameter 1 to be array, string given in /var/www/dev/vendor/eftec/pdoone/lib/PdoOne.php on line 1748
> Job #1 2019-12-26 23:12:30.546100 [ERROR]: save|Failed to run query update `chopsuey_jobs` set `idjob`=?,`idactive`=?,`idstate`=?,`dateinit`=?,`datelastchange`=?,`dateexpired`=?,`dateend`=?,`customerpresent`=?,`addressnotfound`=?,`signeddeliver`=?,`abort`=?,`instock`=?,`picked`=?,`text_job`=? where idjob=? CAUSE: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound. Last query:[update `chopsuey_jobs` set `idjob`=?,`idactive`=?,`idstate`=?,`dateinit`=?,`datelastchange`=?,`dateexpired`=?,`dateend`=?,`customerpresent`=?,`addressnotfound`=?,`signeddeliver`=?,`abort`=?,`instock`=?,`picked`=?,`text_job`=? where idjob=?].
> Job #1 2019-12-26 23:12:30.547200 [INFO]: state|changed|Pick order|1|Transport order|3|change

**Comment by jorgecc** [comment]
Updated, it was a bug on the library eftec/pdoone.  You should update your composer.
