### ISSUE TITLE
Question: Trigger action on a specific state

### ISSUE THREAD

**Issue by johndkn** [EFTEC/StateMachineOne#6]
Hello,

Is it possible to trigger some actions (a function ? a script ?) on a specific state ? 

For example (using the ChopSuey's exercise) if I want to : 
1/ send an email when the food is delivered (i.e. STATE_DELIVERED)
2/ send a SMS when STATE_ABORTTRANSPORT

Thanks in advance

**Comment by jorgecc** [comment]
I updated the example of Chopsuey with it.

There are many ways to call a method:
* global function
* inherited in the class StateMachineOne
* or defined as a method in the service object (the example)

Example:

> $smachine->addEvent(EVENT_CUSTOM_METHOD,'set instock=customMethod(instock)');

note: it is also possible to know the current job using the variable **_idjob**

> $smachine->addEvent(EVENT_CUSTOM_METHOD,'set instock=customMethod(_idjob)');

**Comment by johndkn** [comment]
Awesome, thanks :)
