### ISSUE TITLE
Program structure

### ISSUE THREAD

**Issue by martst** [EFTEC/StateMachineOne#7]
I would like to use your code to solve a couple of simple workflow tasks we have but I don't understand how to include your code.
One of the workflows starts with the completion of a form and then the sending of an email with the details. There will be accept and decline buttons in the email.
I have written all the individual elements and the statemachine but I don't understand how to combine them. Is the statemachine a class/function included/called from each of the external programs? All your examples show a single program but the code needs to be executed when the form is completed and from the program called by the accept/decline URL. Your examples don't show how the field values used to trigger the state transitions are changed.
I apologise if there is an obvious answer but any help is appreciated.

**Comment by jorgecc** [comment]
Hi there:

I don't follow you what do you want to do.

First, you must create a job, and inside the job you put all your information that you want to use, for example, the email, if the button is pressed and such.

If you want to run more than one operation, then you must create more than one job and you can use a foreach() for that.

How the field values are changed? With the business rules and the execution of the job

```php
$smachine->addTransition(STATE1,STATE2,'when value1 = 0 set value2="world"'); //   This transition is just the blueprint of the flow
$job=$smachine->createJob(['value1'=>0,'value2'=>'hello']);  // we create a job with the values that you want to execute
$smachine->checkJob($job); // we check and execute the job (using our blueprint)
// $job->fields['value2'] is equals to ' world'
```

**Comment by martst** [comment]
Thank you for replying.
In the first part of my process I will have a php program file that contains the statemachine logic. It will create the job and when the form is completed the email will be sent. In 1 or 2 days time when the email is read and the accept link is clicked the url will call a php program to continue the job to the next state. The called url will contain the idjob as a parameter.
My question was if I should have 1 program that starts the process and a separate program for later states or 1 large program that does the complete process.
I could have one program file that calls the initial input form function if there are no calling parameters but skips that function if there is an idjob parameter.
I was wondering if there was a simple way to have multiple programs use the same statemachine logic for the same job rather than have 1 large program.

**Comment by jorgecc** [comment]
Sorry for the delay (and I hope that you already are solved) your problem). However, I was checking this request and it is not part of the project. It could do the job but there is a missing part that is not part of the state machine, a schedule tasker.  It also doesn't include the use of emails or anything else. It's up to the developer to design such tasks.
