### ISSUE TITLE
Error in $sMachine->createDbTable(false); method

### ISSUE THREAD

**Issue by dionisvl** [EFTEC/StateMachineOne#8]
Hello
I try to run State Machine from zero on PHP 7.4 and MySQL 8.0
And i get error:
`Fatal error: Uncaught RuntimeException: Error on database Unable to run raw query CREATE TABLE `buymilk_logs` (`idjoblog` INT NOT NULL AUTO_INCREMENT,`idjob` int,`idrel` varchar(200),`type` varchar(50),`description` varchar(2000),`date` timestamp DEFAULT '1970-01-01 00:00:01', PRIMARY KEY(`idjoblog`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 in C:\OSpanel\domains\test\automata\vendor\eftec\pdoone\lib\PdoOne.php:2762 Stack trace: #0 C:\OSpanel\domains\test\automata\vendor\eftec\pdoone\lib\PdoOne.php(4884): eftec\PdoOne->throwError() #1 C:\OSpanel\domains\test\automata\vendor\eftec\pdoone\lib\PdoOne.php(4937): eftec\PdoOne->runMultipleRawQuery() #2 C:\OSpanel\domains\test\automata\vendor\eftec\statemachineone\lib\StateMachineOne.php(623): eftec\PdoOne->createTable() #3 C:\OSpanel\domains\test\automata\index.php(45): eftec\statemachineone\StateMachineOne->createDbTable() #4 {main} thrown in C:\OSpanel\domains\test\automata\vendor\eftec\pdoone\lib\PdoOne.php on line 2762`

i think solve of it problem it is change 
`'date'=>'timestamp DEFAULT \'1970-01-01 00:00:01\'' `
to
`'date'=>'timestamp DEFAULT \'1971-01-01 00:00:01\''`

in these places:
- automata/vendor/eftec/statemachineone/lib/StateMachineOne.php:621
- automata/vendor/eftec/statemachineone/lib/StateMachineOne.php:600

**Comment by jorgecc** [comment]
fixed (a bit later)
I added a new method called $this->zeroDate where you can set the zero date.
